set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

list(APPEND VCPKG_CXX_FLAGS -DBOOST_ALL_DYN_LINK=ON -DBOOST_USE_WINAPI_VERSION=0x0A00 -D_WIN32_WINNT=0x0A00 -DWINVER=0x0A00)
list(APPEND VCPKG_C_FLAGS -DBOOST_ALL_DYN_LINK=ON -DBOOST_USE_WINAPI_VERSION=0x0A00 -D_WIN32_WINNT=0x0A00 -DWINVER=0x0A00)
