set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_C_FLAGS "-DBOOST_USE_WINAPI_VERSION=0x0A00 -D_WIN32_WINNT=0x0A00 -DWINVER=0x0A00")
set(VCPKG_CXX_FLAGS "-DBOOST_USE_WINAPI_VERSION=0x0A00 -D_WIN32_WINNT=0x0A00 -DWINVER=0x0A00")

if (PORT STREQUAL "opentelemetry-cpp")
    set(VCPKG_CMAKE_CONFIGURE_OPTIONS "-DCMAKE_CXX_STANDARD=14 -DCMAKE_CXX_STANDARD_REQUIRED:BOOL=ON -DCMAKE_CXX_EXTENSIONS:BOOL=ON -DCMAKE_MAP_IMPORTED_CONFIG_RELWITHDEBINFO=Debug -DFORCE_STATIC_VCRT:BOOL=ON -DWITH_OTLP_FILE:BOOL=ON -DWITH_EXAMPLES:BOOL=ON -DOPENTELEMETRY_INSTALL:BOOL=ON")
else ()
    set(VCPKG_CMAKE_CONFIGURE_OPTIONS "-DCMAKE_CXX_STANDARD=14 -DCMAKE_CXX_STANDARD_REQUIRED:BOOL=ON -DCMAKE_CXX_EXTENSIONS:BOOL=ON -DCMAKE_MAP_IMPORTED_CONFIG_RELWITHDEBINFO=Debug -DFORCE_STATIC_VCRT:BOOL=ON")
endif ()
