#!/usr/bin/env bash
# The MIT License (MIT)
#
# Copyright © 2022-2025 Stephen G. Tuggy
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

set -e

echo "------------------------------"
echo "--- bootstrap | 2025-12-05 ---"
echo "------------------------------"

platform="$(uname | tr '[:upper:]' '[:lower:]')"

case "$platform" in
    "linux"|"linux-gnu")
        echo "Bootstrapping on Linux..."
        if [ -f ./script/bootstrap-on-linux.sh ] && [ -x ./script/bootstrap-on-linux.sh ]
        then
            . ./script/bootstrap-on-linux.sh "$1"
        elif [ -f ./bootstrap-on-linux.sh ] && [ -x ./bootstrap-on-linux.sh ]
        then
            . ./bootstrap-on-linux.sh "$1"
        else
            echo "Error locating bootstrap-on-linux.sh"
            exit 3
        fi
        ;;
    "darwin")
        echo "Bootstrapping on macOS X or later..."
        if [ -f ./script/bootstrap-on-macOS.sh ] && [ -x ./script/bootstrap-on-macOS.sh ]
        then
            . ./script/bootstrap-on-macOS.sh "$1"
        elif [ -f ./bootstrap-on-macOS.sh ] && [ -x ./bootstrap-on-macOS.sh ]
        then
            . ./bootstrap-on-macOS.sh "$1"
        else
            echo "Error locating bootstrap-on-macOS.sh"
            exit 3
        fi
        ;;
    *)
        echo "Sorry, unrecognized or unsupported operating system"
        exit 2
        ;;
esac

