name: Windows-CI
permissions:
  contents: read
  pull-requests: read

# Controls when the action will run.
on:
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build_and_test:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - preset-name: VS2022Win64-pie-enabled-debug-no-otel
            os: windows-2022
            triplet: x64-win10
            python-version: 3.14.3
          - preset-name: VS2022Win64-pie-enabled-release-no-otel
            os: windows-2022
            triplet: x64-win10
            python-version: 3.14.3
          - preset-name: VS2022Win64-pie-enabled-RelWithDebInfo-no-otel
            os: windows-2022
            triplet: x64-win10
            python-version: 3.14.3
          - preset-name: VS2022Win64-pie-enabled-debug-fetch-use-otel
            os: windows-2022
            triplet: x64-win10
            python-version: 3.14.3
          - preset-name: VS2022Win64-pie-enabled-release-fetch-use-otel
            os: windows-2022
            triplet: x64-win10
            python-version: 3.14.3
          - preset-name: VS2022Win64-pie-enabled-RelWithDebInfo-fetch-use-otel
            os: windows-2022
            triplet: x64-win10
            python-version: 3.14.3
          - preset-name: VS2022Win64-pie-enabled-debug-no-otel
            os: windows-2025
            triplet: x64-win10
            python-version: 3.14.3
          - preset-name: VS2022Win64-pie-enabled-release-no-otel
            os: windows-2025
            triplet: x64-win10
            python-version: 3.14.3
          - preset-name: VS2022Win64-pie-enabled-RelWithDebInfo-no-otel
            os: windows-2025
            triplet: x64-win10
            python-version: 3.14.3
          - preset-name: VS2022Win64-pie-enabled-debug-fetch-use-otel
            os: windows-2025
            triplet: x64-win10
            python-version: 3.14.3
          - preset-name: VS2022Win64-pie-enabled-release-fetch-use-otel
            os: windows-2025
            triplet: x64-win10
            python-version: 3.14.3
          - preset-name: VS2022Win64-pie-enabled-RelWithDebInfo-fetch-use-otel
            os: windows-2025
            triplet: x64-win10
            python-version: 3.14.3
          - preset-name: VS2026Win64-pie-enabled-debug-no-otel
            os: windows-2025-vs2026
            triplet: x64-win10
            python-version: 3.14.3
          - preset-name: VS2026Win64-pie-enabled-release-no-otel
            os: windows-2025-vs2026
            triplet: x64-win10
            python-version: 3.14.3
          - preset-name: VS2026Win64-pie-enabled-RelWithDebInfo-no-otel
            os: windows-2025-vs2026
            triplet: x64-win10
            python-version: 3.14.3
          - preset-name: VS2026Win64-pie-enabled-debug-fetch-use-otel
            os: windows-2025-vs2026
            triplet: x64-win10
            python-version: 3.14.3
          - preset-name: VS2026Win64-pie-enabled-release-fetch-use-otel
            os: windows-2025-vs2026
            triplet: x64-win10
            python-version: 3.14.3
          - preset-name: VS2026Win64-pie-enabled-RelWithDebInfo-fetch-use-otel
            os: windows-2025-vs2026
            triplet: x64-win10
            python-version: 3.14.3

    env:
      # Indicates the location of vcpkg
      VCPKG_ROOT: '${{ github.workspace }}/v'
#      # Tells vcpkg where binary packages are stored.
#      VCPKG_DEFAULT_BINARY_CACHE: '${{ github.workspace }}/vbincache'
      # Let's use GitHub Action cache as storage for the vcpkg Binary Caching feature.
      VCPKG_BINARY_SOURCES: clear;files,${{ github.workspace }}/vcpkg_cache,readwrite
      VCPKG_OVERLAY_PORTS: ${{ github.workspace }}\\custom-triplets
      VCPKG_FEATURE_FLAGS: "manifests,registries"
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}
      VCPKG_DEFAULT_HOST_TRIPLET: ${{ matrix.triplet }}
      PYTHONHOME: ""
      PYTHONPATH: ""

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Restore vcpkg cache
        id: cache-vcpkg-restore
        uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ${{ github.workspace }}/vcpkg_cache
          key: vcpkg_cache-${{ github.repository_owner }}-${{ matrix.os }}-${{ matrix.triplet }}-${{ hashFiles('vcpkg.json') }}

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        id: vega-py-setup
        with:
          python-version: ${{ matrix.python-version }}
          update-environment: false

      - name: Install CMake
        uses: lukka/get-cmake@7bfc9baacbbdcb5e37957ad05c3546b3e222be3c # v4.3.2

      - name: Install vcpkg
        uses: lukka/run-vcpkg@b1a0dd252f06b9e25b3c022a9a03bd7a427fb6a2 # v11.6
        env:
          Python3_ROOT_DIR: ${{ steps.vega-py-setup.outputs.python-path }}
          Python_ROOT_DIR: ${{ steps.vega-py-setup.outputs.python-path }}
          pythonLocation: ${{ steps.vega-py-setup.outputs.python-path }}

      - name: Build and test the code
        uses: lukka/run-cmake@5d55ea7949e25f69f0ecb516d8d572297e03a956 # v10.9
        env:
          Python3_ROOT_DIR: ${{ steps.vega-py-setup.outputs.python-path }}
          Python_ROOT_DIR: ${{ steps.vega-py-setup.outputs.python-path }}
          pythonLocation: ${{ steps.vega-py-setup.outputs.python-path }}
        with:
          configurePreset: ${{ matrix.preset-name }}
          buildPreset: "build-${{ matrix.preset-name }}"
          testPreset: "test-${{ matrix.preset-name }}"

      - name: Save vcpkg cache
        id: cache-vcpkg-save
        uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ${{ github.workspace }}/vcpkg_cache
          key: ${{ steps.cache-vcpkg-restore.outputs.cache-primary-key }}
        if: steps.cache-vcpkg-restore.outputs.cache-hit != 'true'
